### ISSUE TITLE
Support Angular 17

### ISSUE THREAD

**Issue by EthanTuning** [matheo/ngx-sticky-kit#1]
This repo seems to not be used much; however, I am having a hell of a time trying to find an up-to-date library to make sticky elements easy in Angular. Please consider updating this?

**Comment by matheo** [comment]
Hi @EthanTuning 
I just compiled the package and published `ngx-sticky-kit` version 17.0.0
try it out and comment the results please

**Comment by EthanTuning** [comment]
wow! thanks! I will give it a go!
